# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 19:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StormChaser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('zipcode', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inLaundry', models.BooleanField(default=False)),
                ('daysWornBeforeWash', models.IntegerField(default=0)),
                ('daysNotUsed', models.IntegerField(default=0)),
                ('cloth_type', models.IntegerField(choices=[(1, 'TOP'), (2, 'BOTTOM'), (3, 'JACKET'), (4, 'ACCESSORY')], max_length=1)),
                ('cloth_name', models.IntegerField(choices=[(1, 'T-SHIRT'), (2, 'POLO'), (3, 'BUTTONED_SHIRT'), (4, 'JEANS'), (5, 'SHORTS'), (6, 'SWEATS'), (7, 'COAT'), (8, 'HOODIE'), (9, 'SWEATER'), (10, 'EARMUFFS'), (11, 'UMBRELLA'), (12, 'SCARF'), (13, 'GLOVES')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='stormchaser',
            name='wardrobes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clothing.Wardrobe'),
        ),
    ]
