# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stormchaser',
            name='wardrobes',
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='cloth_name',
            field=models.IntegerField(choices=[(1, 'T-SHIRT'), (2, 'POLO'), (3, 'BUTTONED_SHIRT'), (4, 'JEANS'), (5, 'SHORTS'), (6, 'SWEATS'), (7, 'COAT'), (8, 'HOODIE'), (9, 'SWEATER'), (10, 'EARMUFFS'), (11, 'UMBRELLA'), (12, 'SCARF'), (13, 'GLOVES')]),
        ),
        migrations.AlterField(
            model_name='wardrobe',
            name='cloth_type',
            field=models.IntegerField(choices=[(1, 'TOP'), (2, 'BOTTOM'), (3, 'JACKET'), (4, 'ACCESSORY')]),
        ),
    ]
